package br.ufrpe_SistemaAcademia.gui;

import br.ufrpe_SistemaAcademia.exception.ElementoNaoExisteException;
import br.ufrpe_SistemaAcademia.negocio.Fachada;
import br.ufrpe_SistemaAcademia.negocio.bean.Aluno;
import br.ufrpe_SistemaAcademia.negocio.bean.Gerente;
import br.ufrpe_SistemaAcademia.negocio.bean.Professor;
import java.time.LocalDate;
import javax.swing.JOptionPane;

public class TelaGerenteConsultar extends javax.swing.JFrame {

    Gerente usuario = (Gerente)Fachada.getInstance().getUsuario();
    Aluno alunoAchado;
    Professor professorAchado;
    
    public TelaGerenteConsultar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtMatriculaAluno = new javax.swing.JTextField();
        btnConsultarAluno = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnApagarAluno = new javax.swing.JButton();
        lblNomeAluno = new javax.swing.JLabel();
        lblMatriculaAluno = new javax.swing.JLabel();
        lblProfessorDoAluno = new javax.swing.JLabel();
        lblCpfAluno = new javax.swing.JLabel();
        lblVencimentoAluno = new javax.swing.JLabel();
        lblEmailAluno = new javax.swing.JLabel();
        btnEditarAluno = new javax.swing.JButton();
        btnRemoverAluno = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        btnApagarProfessor = new javax.swing.JButton();
        lblNomeProfessor = new javax.swing.JLabel();
        lblSenhaProfessor = new javax.swing.JLabel();
        lblCpfProfessor = new javax.swing.JLabel();
        lbliDProfessor = new javax.swing.JLabel();
        lblEmailProfessor = new javax.swing.JLabel();
        lblQtdAlunosDoProfessor = new javax.swing.JLabel();
        btnRemoverProfessor = new javax.swing.JButton();
        btnEditarProfessor = new javax.swing.JButton();
        btnConsultarProfessor = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        txtIDProfessor = new javax.swing.JTextField();
        btnSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tela do Aluno");

        jPanel1.setBackground(new java.awt.Color(0, 0, 204));

        jLabel1.setBackground(new java.awt.Color(204, 255, 204));
        jLabel1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Academia");

        jLabel2.setBackground(new java.awt.Color(204, 255, 204));
        jLabel2.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Power");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrpe_SistemaAcademia/images/5463870-design-de-logotipo-de-academia-relampago-vetor.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(101, 101, 101))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel2)))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        jPanel2.setPreferredSize(new java.awt.Dimension(600, 400));

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel4.setText("Consultar Alunos");

        jLabel6.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel6.setText("Informe a Matricula do Aluno:");

        btnConsultarAluno.setBackground(new java.awt.Color(0, 0, 204));
        btnConsultarAluno.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnConsultarAluno.setForeground(new java.awt.Color(255, 255, 255));
        btnConsultarAluno.setText("Consultar");
        btnConsultarAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarAlunoActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(153, 153, 153));

        jLabel11.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel11.setText("Matricula:");

        jLabel12.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel12.setText("Professor:");

        jLabel10.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel10.setText("Validade:");

        jLabel7.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel7.setText("Nome:");

        jLabel8.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel8.setText("CPF:");

        jLabel9.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel9.setText("Email:");

        btnApagarAluno.setBackground(new java.awt.Color(0, 0, 204));
        btnApagarAluno.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        btnApagarAluno.setForeground(new java.awt.Color(255, 255, 255));
        btnApagarAluno.setText("Apagar");
        btnApagarAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApagarAlunoActionPerformed(evt);
            }
        });

        lblNomeAluno.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        lblNomeAluno.setText("vazio...");

        lblMatriculaAluno.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        lblMatriculaAluno.setText("vazio...");

        lblProfessorDoAluno.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        lblProfessorDoAluno.setText("vazio...");

        lblCpfAluno.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        lblCpfAluno.setText("vazio...");

        lblVencimentoAluno.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        lblVencimentoAluno.setText("vazio...");

        lblEmailAluno.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        lblEmailAluno.setText("vazio...");

        btnEditarAluno.setBackground(new java.awt.Color(0, 0, 204));
        btnEditarAluno.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnEditarAluno.setForeground(new java.awt.Color(255, 255, 255));
        btnEditarAluno.setText("Editar");
        btnEditarAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarAlunoActionPerformed(evt);
            }
        });

        btnRemoverAluno.setBackground(new java.awt.Color(0, 0, 204));
        btnRemoverAluno.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnRemoverAluno.setForeground(new java.awt.Color(255, 255, 255));
        btnRemoverAluno.setText("Remover");
        btnRemoverAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverAlunoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblNomeAluno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblCpfAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblEmailAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblMatriculaAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblProfessorDoAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblVencimentoAluno, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)))
                        .addGap(16, 16, 16))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(btnEditarAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnRemoverAluno)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnApagarAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(lblNomeAluno)
                    .addComponent(lblCpfAluno)
                    .addComponent(lblEmailAluno))
                .addGap(35, 35, 35)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel10)
                    .addComponent(lblMatriculaAluno)
                    .addComponent(lblProfessorDoAluno)
                    .addComponent(lblVencimentoAluno))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnApagarAluno)
                    .addComponent(btnEditarAluno)
                    .addComponent(btnRemoverAluno))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addGap(201, 201, 201))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMatriculaAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnConsultarAluno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtMatriculaAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConsultarAluno))
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Consultar Aluno", jPanel2);

        jLabel5.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel5.setText("Consultar Professor");

        jPanel5.setBackground(new java.awt.Color(153, 153, 153));

        jLabel13.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel13.setText("Senha:");

        jLabel14.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel14.setText("ID:");

        jLabel15.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel15.setText("Qtd Alunos:");

        jLabel16.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel16.setText("Nome:");

        jLabel17.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel17.setText("CPF:");

        jLabel18.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel18.setText("Email:");

        btnApagarProfessor.setBackground(new java.awt.Color(0, 0, 204));
        btnApagarProfessor.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        btnApagarProfessor.setForeground(new java.awt.Color(255, 255, 255));
        btnApagarProfessor.setText("Apagar");
        btnApagarProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApagarProfessorActionPerformed(evt);
            }
        });

        lblNomeProfessor.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        lblNomeProfessor.setText("vazio...");

        lblSenhaProfessor.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        lblSenhaProfessor.setText("vazio...");

        lblCpfProfessor.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        lblCpfProfessor.setText("vazio...");

        lbliDProfessor.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        lbliDProfessor.setText("vazio...");

        lblEmailProfessor.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        lblEmailProfessor.setText("vazio...");

        lblQtdAlunosDoProfessor.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        lblQtdAlunosDoProfessor.setText("vazio...");

        btnRemoverProfessor.setBackground(new java.awt.Color(0, 0, 204));
        btnRemoverProfessor.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnRemoverProfessor.setForeground(new java.awt.Color(255, 255, 255));
        btnRemoverProfessor.setText("Remover");
        btnRemoverProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverProfessorActionPerformed(evt);
            }
        });

        btnEditarProfessor.setBackground(new java.awt.Color(0, 0, 204));
        btnEditarProfessor.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnEditarProfessor.setForeground(new java.awt.Color(255, 255, 255));
        btnEditarProfessor.setText("Editar");
        btnEditarProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarProfessorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(7, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel16)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNomeProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSenhaProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblCpfProfessor, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                    .addComponent(lbliDProfessor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 19, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblEmailProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblQtdAlunosDoProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnEditarProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnRemoverProfessor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnApagarProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18)
                    .addComponent(lblNomeProfessor)
                    .addComponent(lblCpfProfessor)
                    .addComponent(lblEmailProfessor))
                .addGap(35, 35, 35)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addComponent(lblSenhaProfessor)
                    .addComponent(lbliDProfessor)
                    .addComponent(lblQtdAlunosDoProfessor))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnApagarProfessor)
                    .addComponent(btnRemoverProfessor)
                    .addComponent(btnEditarProfessor))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        btnConsultarProfessor.setBackground(new java.awt.Color(0, 0, 204));
        btnConsultarProfessor.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnConsultarProfessor.setForeground(new java.awt.Color(255, 255, 255));
        btnConsultarProfessor.setText("Consultar");
        btnConsultarProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarProfessorActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel19.setText("Informe ID do Prof:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(192, 192, 192))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtIDProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnConsultarProfessor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(16, 16, 16)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConsultarProfessor)
                    .addComponent(jLabel19)
                    .addComponent(txtIDProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Consultar Professor", jPanel3);

        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTabbedPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSair)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(btnSair)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        this.dispose();
        new TelaGerente().setVisible(true);
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnConsultarAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarAlunoActionPerformed
        
        String matricula = txtMatriculaAluno.getText();
        
        Aluno a = new Aluno();
        a.setMatricula(matricula);
        
        try {
            
            alunoAchado = (Aluno)Fachada.getInstance().consultar(usuario, a);
            
            Fachada.getInstance().setPessoaManipulada(alunoAchado);
            
            lblCpfAluno.setText(alunoAchado.getCpf());
            lblEmailAluno.setText(alunoAchado.getEmail());
            lblMatriculaAluno.setText(alunoAchado.getMatricula());
            lblNomeAluno.setText(alunoAchado.getNome());
            lblProfessorDoAluno.setText(alunoAchado.getProfessor().getNome());
            
            if(alunoAchado.getPlanoPagamento() != null){
                LocalDate dataVencimento = alunoAchado.getPlanoPagamento().getDataFim();
                String data = Fachada.getInstance().dateParaString(dataVencimento);

                lblVencimentoAluno.setText(data);
            }else{
                lblVencimentoAluno.setText("Sem plano!");
            }
            
            
        } catch (ElementoNaoExisteException ex) {
            
            limparCamposAluno();
            
            JOptionPane.showMessageDialog(null, ex.getMessage(), "ERRO", 0);
        }
        
    }//GEN-LAST:event_btnConsultarAlunoActionPerformed

    private void btnApagarAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApagarAlunoActionPerformed
        
        limparCamposAluno();
    }//GEN-LAST:event_btnApagarAlunoActionPerformed

    private void btnRemoverAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverAlunoActionPerformed
        
        if(alunoAchado != null){
            
            try {
                
                int i = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja excluir " 
                        + alunoAchado.getNome() + "?", "CONFIRMAÇÃO", 1);
                
                if(i == 0){
                    
                    Fachada.getInstance().remover(usuario, alunoAchado);
                    
                    Fachada.getInstance().salvarPessoasNoArquivo("pessoas.dat");
                    
                    JOptionPane.showMessageDialog(null, "Aluno excluido com sucesso!", "ATENÇÃO", 1);
                    limparCamposAluno();
                    
                }else{
                    JOptionPane.showMessageDialog(null, "Aluno não foi excluido!", "ATENÇÃO", 1);
                }
                
                
            
            } catch (ElementoNaoExisteException ex) {

                limparCamposAluno();
                JOptionPane.showMessageDialog(null, ex.getMessage(), "ERRO", 0);
            }
        }else{
            JOptionPane.showMessageDialog(null, "Selecione um aluno antes!", "ERRO", 0);
        }
        
    }//GEN-LAST:event_btnRemoverAlunoActionPerformed

    private void btnEditarAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarAlunoActionPerformed
        
        Fachada.getInstance().setPessoaManipulada(alunoAchado);
        
        if(Fachada.getInstance().getPessoaManipulada() != null){
            
            int i = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja editar o/a aluno/a " 
                        + Fachada.getInstance().getPessoaManipulada().getNome() + "?", "CONFIRMAÇÃO", 1);
            
            if(i == 0){
                new TelaGerenteEditar().setVisible(true);
                this.dispose();
            }            
        }else{
            JOptionPane.showMessageDialog(null, "Selecione o aluno para ser editado!", "ERRO", 0);
        }
    }//GEN-LAST:event_btnEditarAlunoActionPerformed

    private void btnConsultarProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarProfessorActionPerformed
        
        String idProfessor = txtIDProfessor.getText();
        
        Professor a = new Professor();
        a.setId_Professor(idProfessor);
        
        try {
            
            professorAchado = (Professor)Fachada.getInstance().consultar(usuario, a);
            
            Fachada.getInstance().setPessoaManipulada(professorAchado);
            
            lblCpfProfessor.setText(professorAchado.getCpf());
            lblEmailProfessor.setText(professorAchado.getEmail());
            lbliDProfessor.setText(professorAchado.getId_Professor());
            lblNomeProfessor.setText(professorAchado.getNome());
            lblSenhaProfessor.setText(professorAchado.getSenha());
            
            int i = professorAchado.getAlunos().size();
            String qtdAlunos = String.valueOf(i);
            
            lblQtdAlunosDoProfessor.setText(qtdAlunos);
            
        } catch (ElementoNaoExisteException ex) {
            
            limparCamposProfessor();
            
            JOptionPane.showMessageDialog(null, ex.getMessage(), "ERRO", 0);
        }
    }//GEN-LAST:event_btnConsultarProfessorActionPerformed

    private void btnApagarProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApagarProfessorActionPerformed
        
        limparCamposProfessor();
    }//GEN-LAST:event_btnApagarProfessorActionPerformed

    private void btnRemoverProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverProfessorActionPerformed
        
        if(professorAchado != null){
            
            try {
                
                int i = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja excluir " 
                        + professorAchado.getNome() + "?", "CONFIRMAÇÃO", 1);
                
                if(i == 0){
                    
                    Fachada.getInstance().remover(usuario, professorAchado);
                    
                    Fachada.getInstance().salvarPessoasNoArquivo("pessoas.dat");
                    
                    JOptionPane.showMessageDialog(null, "Professor excluido com sucesso!", "ATENÇÃO", 1);
                    
                    limparCamposProfessor();
                    
                }else{
                    JOptionPane.showMessageDialog(null, "Professor não foi excluido!", "ATENÇÃO", 1);
                }               
            
            } catch (ElementoNaoExisteException ex) {

                limparCamposProfessor();
                JOptionPane.showMessageDialog(null, ex.getMessage(), "ERRO", 0);
            }
        }else{
            JOptionPane.showMessageDialog(null, "Selecione um professor antes!", "ERRO", 0);
        }
    }//GEN-LAST:event_btnRemoverProfessorActionPerformed

    private void btnEditarProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarProfessorActionPerformed
        
        Fachada.getInstance().setPessoaManipulada(professorAchado);
        
        if(Fachada.getInstance().getPessoaManipulada() != null){
            
            int i = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja editar o/a professor/a " 
                        + Fachada.getInstance().getPessoaManipulada().getNome() + "?", "CONFIRMAÇÃO", 1);
            
            if(i == 0){
                new TelaGerenteEditar().setVisible(true);
                this.dispose();
            }            
        }else{
            JOptionPane.showMessageDialog(null, "Selecione o professor para ser editado!", "ERRO", 0);
        }
        
    }//GEN-LAST:event_btnEditarProfessorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaGerenteConsultar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaGerenteConsultar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaGerenteConsultar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaGerenteConsultar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaGerenteConsultar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApagarAluno;
    private javax.swing.JButton btnApagarProfessor;
    private javax.swing.JButton btnConsultarAluno;
    private javax.swing.JButton btnConsultarProfessor;
    private javax.swing.JButton btnEditarAluno;
    private javax.swing.JButton btnEditarProfessor;
    private javax.swing.JButton btnRemoverAluno;
    private javax.swing.JButton btnRemoverProfessor;
    private javax.swing.JButton btnSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblCpfAluno;
    private javax.swing.JLabel lblCpfProfessor;
    private javax.swing.JLabel lblEmailAluno;
    private javax.swing.JLabel lblEmailProfessor;
    private javax.swing.JLabel lblMatriculaAluno;
    private javax.swing.JLabel lblNomeAluno;
    private javax.swing.JLabel lblNomeProfessor;
    private javax.swing.JLabel lblProfessorDoAluno;
    private javax.swing.JLabel lblQtdAlunosDoProfessor;
    private javax.swing.JLabel lblSenhaProfessor;
    private javax.swing.JLabel lblVencimentoAluno;
    private javax.swing.JLabel lbliDProfessor;
    private javax.swing.JTextField txtIDProfessor;
    private javax.swing.JTextField txtMatriculaAluno;
    // End of variables declaration//GEN-END:variables

    public void limparCamposAluno(){
        
        txtMatriculaAluno.setText("");
        lblCpfAluno.setText("");
        lblEmailAluno.setText("");
        lblMatriculaAluno.setText("");
        lblNomeAluno.setText("");
        lblProfessorDoAluno.setText("");
        lblVencimentoAluno.setText("");
        
        alunoAchado = null;
    }
    
    public void limparCamposProfessor(){
        
        txtIDProfessor.setText("");
        lblCpfProfessor.setText("");
        lblEmailProfessor.setText("");
        lbliDProfessor.setText("");
        lblNomeProfessor.setText("");
        lblSenhaProfessor.setText("");
        lblQtdAlunosDoProfessor.setText("");
        
        professorAchado = null;
    }
   
}
